version: '3'


services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
    environment:
      - CF_API_EMAIL=${YOUR EMAIL}
#     - CF_API_EMAIL=exmple@gmail.com 
      - CF_DNS_API_TOKEN=${USE YOUR CLOUDFLARE TOKEN}
      # - CF_API_KEY=YOU_API_KEY
      # be sure to use the correct one depending on if you are using a token or key
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/home/pi/code/traefik/data/traefik.yml:/traefik.yml:ro"
      - "/home/pi/code/traefik/data/acme.json:/acme.json"
      #  Next left in as example for adding a second certificate resolver
#     - "/home/pi/code/traefik/data/syn-acme.json:/syn-acme.json"
      - "/home/pi/code/traefik/data/config.yml:/config.yml:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=name:password"
    # - "traefik.http.middlewares.traefik-auth.basicauth.users=brock:$$apr1$$PZzmtDJHfggAbddNhKs.E9dYKsl3Mqz/"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=websecure"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.traefik-secure.entrypoints=web,websecure"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik-dashboard.example.com`)"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=cloudflare" #There are other resolvers available
      - "traefik.http.routers.traefik-secure.tls.domains[0].main=example.com"
      - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.example.com"
      - "traefik.http.routers.traefik-secure.service=api@internal"

#This is an essential step
networks:
  proxy:
    external: true
